BambooTracker/gui/instrument_editor/fm_instrument_editor.cpp: Fix deprecated-declarations warning
QCheckBox::stateChanged got replaced by QCheckBox::checkStateChanged in Qt 6.7.

gui/instrument_editor/fm_instrument_editor.cpp: In constructor 'FmInstrumentEditor::FmInstrumentEditor(int, QWidget*)':
gui/instrument_editor/fm_instrument_editor.cpp:280:57: error: 'void QCheckBox::stateChanged(int)' is deprecated: Use checkStateChanged() instead [-Werror=deprecated-declarations]
  280 |         QObject::connect(ui->amOp1CheckBox, &QCheckBox::stateChanged,
      |                                                         ^~~~~~~~~~~~
In file included from /usr/include/qt6/QtWidgets/QCheckBox:1,
                 from ./ui_fm_instrument_editor.h:14,
                 from gui/instrument_editor/fm_instrument_editor.cpp:27:
/usr/include/qt6/QtWidgets/qcheckbox.h:41:10: note: declared here
   41 |     void stateChanged(int);
      |          ^~~~~~~~~~~~