Fix compiler error with clang15
This fixes the following compiler error since -Werror is used:

```
gui/order_list_editor/order_list_panel.cpp:712:43: error: variable 'trackVisIdx' set but not used [-Werror,-Wunused-but-set-variable]
        for (int x = rowNumWidth_ + trackWidth_, trackVisIdx = leftTrackVisIdx_; x <= maxWidth; ++trackVisIdx) {
                                                 ^
1 error generated.
```